### PR TITLE
Add a linting workflow based on SuperLinter

### PR DESCRIPTION
**Pull request by dshevtsov**
## Description

Adding a linting workflow based on SuperLinter and setting the Markdown ruleset.
The workflow will be triggered by a GitHub Action on a pull request to the main branch. 
It will check the following:
- only the files changed in a pull request
- workflow files (https://github.com/rhysd/actionlint)
- secrets' leaks (https://github.com/zricethezav/gitleaks)
- Markdown style (https://github.com/igorshubovych/markdownlint-cli)
- YAML format (https://github.com/adrienverge/yamllint)

## Related Issue

#79, #80

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jeff-matthews** [comment]
@dshevtsov, have you considered making the new workflow less specific to linting so that it can accommodate additional PR validation jobs/steps in the future, like internal link checking?

See https://github.com/AdobeDocs/commerce-marketplace/blob/main/.github/workflows/pull-request.yml for an example.

**Comment by dshevtsov** [comment]
@jeff-matthews I was thinking about making the changes gradually, one by one. But you are right, it makes sense to reserve the workflow for future checks related to PR testing.

**Comment by timkim** [comment]
Lgtm but we do need to run the lint against the existing files so they are up to spec. That will be a TODO for me.

**Review by timkim — APPROVED** [review]

**Comment by dshevtsov** [comment]
Fixes #80

**Pull request merged**
